# Generated by Django 4.2.6 on 2023-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_menuitem_menu_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
